### ISSUE TITLE
Does not work on Ubuntu 16.04 64bit

### ISSUE THREAD

**Issue by Unlym** [albertyw/ios-cert-enrollment#10]
I want enroll ipad 2 and ipad air, IOS 9.3.5 and 10.2
When I run ios-cert-enrollment on Ubuntu 14.04 64bit all work, but on 16.04 doesn't work

Teminal:

> [2017-01-27 15:31:15] INFO  WEBrick 1.3.1
> [2017-01-27 15:31:15] INFO  ruby 2.3.1 (2016-04-26) [x86_64-linux-gnu]
> [2017-01-27 15:31:15] INFO  

> [2017-01-27 15:33:15] DEBUG accept: 10.**.**.*:51184
> [2017-01-27 15:33:15] DEBUG Rack::Handler::WEBrick is invoked.
> 10.31.30.5 - - [27/Jan/2017:15:33:15 EET] "GET /?operation=GetCACert HTTP/1.1" 200 944
> - -> /?operation=GetCACert
> [2017-01-27 15:33:15] DEBUG Rack::Handler::WEBrick is invoked.
> 10.31.30.5 - - [27/Jan/2017:15:33:15 EET] "POST /?operation=PKIOperation HTTP/1.1" 200 2798
> - -> /?operation=PKIOperation
> [2017-01-27 15:33:45] DEBUG close: 10.**.**.*:51184

IOS Console:

> 1/27/17, 3:33:18 PM profiled[388]: (Error) MC: Installation failed. Error: NSError:
> 	Desc   : Profile Installation Failed
> 	Sugg   : The SCEP server returned an invalid response.
> 	US Desc: Profile Installation Failed
> 	US Sugg: The SCEP server returned an invalid response.
> 	Domain : MCInstallationErrorDomain
> 	Code   : 4001
> 	Type   : MCFatalError
> 	...Underlying error:
> 	NSError:
> 	Desc   : The SCEP server returned an invalid response.
> 	US Desc: The SCEP server returned an invalid response.
> 	Domain : MCSCEPErrorDomain
> 	Code   : 22013
> 	Type   : MCFatalError
> 	Extra info:
> 	{
> 	   isPrimary = 1;
> 	}
>

**Comment by jeremybdk** [comment]
Hey @Unlym ,
Did you manage to solve this?

Thanks

**Comment by Unlym** [comment]
Hello
I used  https://github.com/micromdm/scep
